# ConfigFireFox.yml
# StarVS browser config
# tabby1

# This is a demo configuration file for StarVS, designed to run in Firefox
# This config file is incomplete/not yet functional. It is a demo file.
starvs-version: "0.0.1"
browser: "Firefox"
useragent: "Mozilla/5.0"
vc: True
# Version control is on
tabs: [ "tabs.xml" , "profileList.json" , "stats.yml" ]
generate-stats: True
# Stats to generate
pinned-tab-count: 0
unpinned-tab-count: 0
record-pinned-tabs: 0
record-unpinned-tabs: 0
closed-tabs: 0

range8: [ "1970" , "2048" ] # Not going by integers, as there is no way I will make it only go to year 256 CE. There is a different way of doing this, I just don't know it right now.
range16: [ "1970" , "2048" ] # 11 bit integer, for 16 bit processors, everything else seemed too high, or too low
range32: [ "1970" , "65536" ] # 16 bit integer, for 32 bit processors
range64: [ "1970" , "2147483648" ] # 32 bit integer, for 64 bit processors
range128: [ "0" , "18446744073709551615" ] # 64 bit integer, for 128 bit processors
range256: [ "0" , "340282366920938463463374607431768211455" ] # 128 bit integer, for 256 bit processors

# File version: 1 (2023, Friday, June 2nd at 4:05 pm PST)
